namespace Octogami.ProviderDirectory.NpiDataProcessor
{
	public class NpiRow
	{
		public string NPI { get; set; }
		public string EntityTypeCode { get; set; }
		public string ReplacementNPI { get; set; }
		public string EmployerIdentificationNumberEin { get; set; }
		public string ProviderOrganizationNameLegalBusinessName { get; set; }
		public string ProviderLastNameLegalName { get; set; }
		public string ProviderFirstName { get; set; }
		public string ProviderMiddleName { get; set; }
		public string ProviderNamePrefixText { get; set; }
		public string ProviderNameSuffixText { get; set; }
		public string ProviderCredentialText { get; set; }
		public string ProviderOtherOrganizationName { get; set; }
		public string ProviderOtherOrganizationNameTypeCode { get; set; }
		public string ProviderOtherLastName { get; set; }
		public string ProviderOtherFirstName { get; set; }
		public string ProviderOtherMiddleName { get; set; }
		public string ProviderOtherNamePrefixText { get; set; }
		public string ProviderOtherNameSuffixText { get; set; }
		public string ProviderOtherCredentialText { get; set; }
		public string ProviderOtherLastNameTypeCode { get; set; }
		public string ProviderFirstLineBusinessMailingAddress { get; set; }
		public string ProviderSecondLineBusinessMailingAddress { get; set; }
		public string ProviderBusinessMailingAddressCityName { get; set; }
		public string ProviderBusinessMailingAddressStateName { get; set; }
		public string ProviderBusinessMailingAddressPostalCode { get; set; }
		public string ProviderBusinessMailingAddressCountryCodeIfOutsideUs { get; set; }
		public string ProviderBusinessMailingAddressTelephoneNumber { get; set; }
		public string ProviderBusinessMailingAddressFaxNumber { get; set; }
		public string ProviderFirstLineBusinessPracticeLocationAddress { get; set; }
		public string ProviderSecondLineBusinessPracticeLocationAddress { get; set; }
		public string ProviderBusinessPracticeLocationAddressCityName { get; set; }
		public string ProviderBusinessPracticeLocationAddressStateName { get; set; }
		public string ProviderBusinessPracticeLocationAddressPostalCode { get; set; }
		public string ProviderBusinessPracticeLocationAddressCountryCodeIfOutsideUs { get; set; }
		public string ProviderBusinessPracticeLocationAddressTelephoneNumber { get; set; }
		public string ProviderBusinessPracticeLocationAddressFaxNumber { get; set; }
		public string ProviderEnumerationDate { get; set; }
		public string LastUpdateDate { get; set; }
		public string NPIDeactivationReasonCode { get; set; }
		public string NPIDeactivationDate { get; set; }
		public string NPIReactivationDate { get; set; }
		public string ProviderGenderCode { get; set; }
		public string AuthorizedOfficialLastName { get; set; }
		public string AuthorizedOfficialFirstName { get; set; }
		public string AuthorizedOfficialMiddleName { get; set; }
		public string AuthorizedOfficialTitleOrPosition { get; set; }
		public string AuthorizedOfficialTelephoneNumber { get; set; }
		public string HealthcareProviderTaxonomyCode1 { get; set; }
		public string ProviderLicenseNumber1 { get; set; }
		public string ProviderLicenseNumberStateCode1 { get; set; }
		public string HealthcareProviderPrimaryTaxonomySwitch1 { get; set; }
		public string HealthcareProviderTaxonomyCode2 { get; set; }
		public string ProviderLicenseNumber2 { get; set; }
		public string ProviderLicenseNumberStateCode2 { get; set; }
		public string HealthcareProviderPrimaryTaxonomySwitch2 { get; set; }
		public string HealthcareProviderTaxonomyCode3 { get; set; }
		public string ProviderLicenseNumber3 { get; set; }
		public string ProviderLicenseNumberStateCode3 { get; set; }
		public string HealthcareProviderPrimaryTaxonomySwitch3 { get; set; }
		public string HealthcareProviderTaxonomyCode4 { get; set; }
		public string ProviderLicenseNumber4 { get; set; }
		public string ProviderLicenseNumberStateCode4 { get; set; }
		public string HealthcareProviderPrimaryTaxonomySwitch4 { get; set; }
		public string HealthcareProviderTaxonomyCode5 { get; set; }
		public string ProviderLicenseNumber5 { get; set; }
		public string ProviderLicenseNumberStateCode5 { get; set; }
		public string HealthcareProviderPrimaryTaxonomySwitch5 { get; set; }
		public string HealthcareProviderTaxonomyCode6 { get; set; }
		public string ProviderLicenseNumber6 { get; set; }
		public string ProviderLicenseNumberStateCode6 { get; set; }
		public string HealthcareProviderPrimaryTaxonomySwitch6 { get; set; }
		public string HealthcareProviderTaxonomyCode7 { get; set; }
		public string ProviderLicenseNumber7 { get; set; }
		public string ProviderLicenseNumberStateCode7 { get; set; }
		public string HealthcareProviderPrimaryTaxonomySwitch7 { get; set; }
		public string HealthcareProviderTaxonomyCode8 { get; set; }
		public string ProviderLicenseNumber8 { get; set; }
		public string ProviderLicenseNumberStateCode8 { get; set; }
		public string HealthcareProviderPrimaryTaxonomySwitch8 { get; set; }
		public string HealthcareProviderTaxonomyCode9 { get; set; }
		public string ProviderLicenseNumber9 { get; set; }
		public string ProviderLicenseNumberStateCode9 { get; set; }
		public string HealthcareProviderPrimaryTaxonomySwitch9 { get; set; }
		public string HealthcareProviderTaxonomyCode10 { get; set; }
		public string ProviderLicenseNumber10 { get; set; }
		public string ProviderLicenseNumberStateCode10 { get; set; }
		public string HealthcareProviderPrimaryTaxonomySwitch10 { get; set; }
		public string HealthcareProviderTaxonomyCode11 { get; set; }
		public string ProviderLicenseNumber11 { get; set; }
		public string ProviderLicenseNumberStateCode11 { get; set; }
		public string HealthcareProviderPrimaryTaxonomySwitch11 { get; set; }
		public string HealthcareProviderTaxonomyCode12 { get; set; }
		public string ProviderLicenseNumber12 { get; set; }
		public string ProviderLicenseNumberStateCode12 { get; set; }
		public string HealthcareProviderPrimaryTaxonomySwitch12 { get; set; }
		public string HealthcareProviderTaxonomyCode13 { get; set; }
		public string ProviderLicenseNumber13 { get; set; }
		public string ProviderLicenseNumberStateCode13 { get; set; }
		public string HealthcareProviderPrimaryTaxonomySwitch13 { get; set; }
		public string HealthcareProviderTaxonomyCode14 { get; set; }
		public string ProviderLicenseNumber14 { get; set; }
		public string ProviderLicenseNumberStateCode14 { get; set; }
		public string HealthcareProviderPrimaryTaxonomySwitch14 { get; set; }
		public string HealthcareProviderTaxonomyCode15 { get; set; }
		public string ProviderLicenseNumber15 { get; set; }
		public string ProviderLicenseNumberStateCode15 { get; set; }
		public string HealthcareProviderPrimaryTaxonomySwitch15 { get; set; }
		public string OtherProviderIdentifier1 { get; set; }
		public string OtherProviderIdentifierTypeCode1 { get; set; }
		public string OtherProviderIdentifierState1 { get; set; }
		public string OtherProviderIdentifierIssuer1 { get; set; }
		public string OtherProviderIdentifier2 { get; set; }
		public string OtherProviderIdentifierTypeCode2 { get; set; }
		public string OtherProviderIdentifierState2 { get; set; }
		public string OtherProviderIdentifierIssuer2 { get; set; }
		public string OtherProviderIdentifier3 { get; set; }
		public string OtherProviderIdentifierTypeCode3 { get; set; }
		public string OtherProviderIdentifierState3 { get; set; }
		public string OtherProviderIdentifierIssuer3 { get; set; }
		public string OtherProviderIdentifier4 { get; set; }
		public string OtherProviderIdentifierTypeCode4 { get; set; }
		public string OtherProviderIdentifierState4 { get; set; }
		public string OtherProviderIdentifierIssuer4 { get; set; }
		public string OtherProviderIdentifier5 { get; set; }
		public string OtherProviderIdentifierTypeCode5 { get; set; }
		public string OtherProviderIdentifierState5 { get; set; }
		public string OtherProviderIdentifierIssuer5 { get; set; }
		public string OtherProviderIdentifier6 { get; set; }
		public string OtherProviderIdentifierTypeCode6 { get; set; }
		public string OtherProviderIdentifierState6 { get; set; }
		public string OtherProviderIdentifierIssuer6 { get; set; }
		public string OtherProviderIdentifier7 { get; set; }
		public string OtherProviderIdentifierTypeCode7 { get; set; }
		public string OtherProviderIdentifierState7 { get; set; }
		public string OtherProviderIdentifierIssuer7 { get; set; }
		public string OtherProviderIdentifier8 { get; set; }
		public string OtherProviderIdentifierTypeCode8 { get; set; }
		public string OtherProviderIdentifierState8 { get; set; }
		public string OtherProviderIdentifierIssuer8 { get; set; }
		public string OtherProviderIdentifier9 { get; set; }
		public string OtherProviderIdentifierTypeCode9 { get; set; }
		public string OtherProviderIdentifierState9 { get; set; }
		public string OtherProviderIdentifierIssuer9 { get; set; }
		public string OtherProviderIdentifier10 { get; set; }
		public string OtherProviderIdentifierTypeCode10 { get; set; }
		public string OtherProviderIdentifierState10 { get; set; }
		public string OtherProviderIdentifierIssuer10 { get; set; }
		public string OtherProviderIdentifier11 { get; set; }
		public string OtherProviderIdentifierTypeCode11 { get; set; }
		public string OtherProviderIdentifierState11 { get; set; }
		public string OtherProviderIdentifierIssuer11 { get; set; }
		public string OtherProviderIdentifier12 { get; set; }
		public string OtherProviderIdentifierTypeCode12 { get; set; }
		public string OtherProviderIdentifierState12 { get; set; }
		public string OtherProviderIdentifierIssuer12 { get; set; }
		public string OtherProviderIdentifier13 { get; set; }
		public string OtherProviderIdentifierTypeCode13 { get; set; }
		public string OtherProviderIdentifierState13 { get; set; }
		public string OtherProviderIdentifierIssuer13 { get; set; }
		public string OtherProviderIdentifier14 { get; set; }
		public string OtherProviderIdentifierTypeCode14 { get; set; }
		public string OtherProviderIdentifierState14 { get; set; }
		public string OtherProviderIdentifierIssuer14 { get; set; }
		public string OtherProviderIdentifier15 { get; set; }
		public string OtherProviderIdentifierTypeCode15 { get; set; }
		public string OtherProviderIdentifierState15 { get; set; }
		public string OtherProviderIdentifierIssuer15 { get; set; }
		public string OtherProviderIdentifier16 { get; set; }
		public string OtherProviderIdentifierTypeCode16 { get; set; }
		public string OtherProviderIdentifierState16 { get; set; }
		public string OtherProviderIdentifierIssuer16 { get; set; }
		public string OtherProviderIdentifier17 { get; set; }
		public string OtherProviderIdentifierTypeCode17 { get; set; }
		public string OtherProviderIdentifierState17 { get; set; }
		public string OtherProviderIdentifierIssuer17 { get; set; }
		public string OtherProviderIdentifier18 { get; set; }
		public string OtherProviderIdentifierTypeCode18 { get; set; }
		public string OtherProviderIdentifierState18 { get; set; }
		public string OtherProviderIdentifierIssuer18 { get; set; }
		public string OtherProviderIdentifier19 { get; set; }
		public string OtherProviderIdentifierTypeCode19 { get; set; }
		public string OtherProviderIdentifierState19 { get; set; }
		public string OtherProviderIdentifierIssuer19 { get; set; }
		public string OtherProviderIdentifier20 { get; set; }
		public string OtherProviderIdentifierTypeCode20 { get; set; }
		public string OtherProviderIdentifierState20 { get; set; }
		public string OtherProviderIdentifierIssuer20 { get; set; }
		public string OtherProviderIdentifier21 { get; set; }
		public string OtherProviderIdentifierTypeCode21 { get; set; }
		public string OtherProviderIdentifierState21 { get; set; }
		public string OtherProviderIdentifierIssuer21 { get; set; }
		public string OtherProviderIdentifier22 { get; set; }
		public string OtherProviderIdentifierTypeCode22 { get; set; }
		public string OtherProviderIdentifierState22 { get; set; }
		public string OtherProviderIdentifierIssuer22 { get; set; }
		public string OtherProviderIdentifier23 { get; set; }
		public string OtherProviderIdentifierTypeCode23 { get; set; }
		public string OtherProviderIdentifierState23 { get; set; }
		public string OtherProviderIdentifierIssuer23 { get; set; }
		public string OtherProviderIdentifier24 { get; set; }
		public string OtherProviderIdentifierTypeCode24 { get; set; }
		public string OtherProviderIdentifierState24 { get; set; }
		public string OtherProviderIdentifierIssuer24 { get; set; }
		public string OtherProviderIdentifier25 { get; set; }
		public string OtherProviderIdentifierTypeCode25 { get; set; }
		public string OtherProviderIdentifierState25 { get; set; }
		public string OtherProviderIdentifierIssuer25 { get; set; }
		public string OtherProviderIdentifier26 { get; set; }
		public string OtherProviderIdentifierTypeCode26 { get; set; }
		public string OtherProviderIdentifierState26 { get; set; }
		public string OtherProviderIdentifierIssuer26 { get; set; }
		public string OtherProviderIdentifier27 { get; set; }
		public string OtherProviderIdentifierTypeCode27 { get; set; }
		public string OtherProviderIdentifierState27 { get; set; }
		public string OtherProviderIdentifierIssuer27 { get; set; }
		public string OtherProviderIdentifier28 { get; set; }
		public string OtherProviderIdentifierTypeCode28 { get; set; }
		public string OtherProviderIdentifierState28 { get; set; }
		public string OtherProviderIdentifierIssuer28 { get; set; }
		public string OtherProviderIdentifier29 { get; set; }
		public string OtherProviderIdentifierTypeCode29 { get; set; }
		public string OtherProviderIdentifierState29 { get; set; }
		public string OtherProviderIdentifierIssuer29 { get; set; }
		public string OtherProviderIdentifier30 { get; set; }
		public string OtherProviderIdentifierTypeCode30 { get; set; }
		public string OtherProviderIdentifierState30 { get; set; }
		public string OtherProviderIdentifierIssuer30 { get; set; }
		public string OtherProviderIdentifier31 { get; set; }
		public string OtherProviderIdentifierTypeCode31 { get; set; }
		public string OtherProviderIdentifierState31 { get; set; }
		public string OtherProviderIdentifierIssuer31 { get; set; }
		public string OtherProviderIdentifier32 { get; set; }
		public string OtherProviderIdentifierTypeCode32 { get; set; }
		public string OtherProviderIdentifierState32 { get; set; }
		public string OtherProviderIdentifierIssuer32 { get; set; }
		public string OtherProviderIdentifier33 { get; set; }
		public string OtherProviderIdentifierTypeCode33 { get; set; }
		public string OtherProviderIdentifierState33 { get; set; }
		public string OtherProviderIdentifierIssuer33 { get; set; }
		public string OtherProviderIdentifier34 { get; set; }
		public string OtherProviderIdentifierTypeCode34 { get; set; }
		public string OtherProviderIdentifierState34 { get; set; }
		public string OtherProviderIdentifierIssuer34 { get; set; }
		public string OtherProviderIdentifier35 { get; set; }
		public string OtherProviderIdentifierTypeCode35 { get; set; }
		public string OtherProviderIdentifierState35 { get; set; }
		public string OtherProviderIdentifierIssuer35 { get; set; }
		public string OtherProviderIdentifier36 { get; set; }
		public string OtherProviderIdentifierTypeCode36 { get; set; }
		public string OtherProviderIdentifierState36 { get; set; }
		public string OtherProviderIdentifierIssuer36 { get; set; }
		public string OtherProviderIdentifier37 { get; set; }
		public string OtherProviderIdentifierTypeCode37 { get; set; }
		public string OtherProviderIdentifierState37 { get; set; }
		public string OtherProviderIdentifierIssuer37 { get; set; }
		public string OtherProviderIdentifier38 { get; set; }
		public string OtherProviderIdentifierTypeCode38 { get; set; }
		public string OtherProviderIdentifierState38 { get; set; }
		public string OtherProviderIdentifierIssuer38 { get; set; }
		public string OtherProviderIdentifier39 { get; set; }
		public string OtherProviderIdentifierTypeCode39 { get; set; }
		public string OtherProviderIdentifierState39 { get; set; }
		public string OtherProviderIdentifierIssuer39 { get; set; }
		public string OtherProviderIdentifier40 { get; set; }
		public string OtherProviderIdentifierTypeCode40 { get; set; }
		public string OtherProviderIdentifierState40 { get; set; }
		public string OtherProviderIdentifierIssuer40 { get; set; }
		public string OtherProviderIdentifier41 { get; set; }
		public string OtherProviderIdentifierTypeCode41 { get; set; }
		public string OtherProviderIdentifierState41 { get; set; }
		public string OtherProviderIdentifierIssuer41 { get; set; }
		public string OtherProviderIdentifier42 { get; set; }
		public string OtherProviderIdentifierTypeCode42 { get; set; }
		public string OtherProviderIdentifierState42 { get; set; }
		public string OtherProviderIdentifierIssuer42 { get; set; }
		public string OtherProviderIdentifier43 { get; set; }
		public string OtherProviderIdentifierTypeCode43 { get; set; }
		public string OtherProviderIdentifierState43 { get; set; }
		public string OtherProviderIdentifierIssuer43 { get; set; }
		public string OtherProviderIdentifier44 { get; set; }
		public string OtherProviderIdentifierTypeCode44 { get; set; }
		public string OtherProviderIdentifierState44 { get; set; }
		public string OtherProviderIdentifierIssuer44 { get; set; }
		public string OtherProviderIdentifier45 { get; set; }
		public string OtherProviderIdentifierTypeCode45 { get; set; }
		public string OtherProviderIdentifierState45 { get; set; }
		public string OtherProviderIdentifierIssuer45 { get; set; }
		public string OtherProviderIdentifier46 { get; set; }
		public string OtherProviderIdentifierTypeCode46 { get; set; }
		public string OtherProviderIdentifierState46 { get; set; }
		public string OtherProviderIdentifierIssuer46 { get; set; }
		public string OtherProviderIdentifier47 { get; set; }
		public string OtherProviderIdentifierTypeCode47 { get; set; }
		public string OtherProviderIdentifierState47 { get; set; }
		public string OtherProviderIdentifierIssuer47 { get; set; }
		public string OtherProviderIdentifier48 { get; set; }
		public string OtherProviderIdentifierTypeCode48 { get; set; }
		public string OtherProviderIdentifierState48 { get; set; }
		public string OtherProviderIdentifierIssuer48 { get; set; }
		public string OtherProviderIdentifier49 { get; set; }
		public string OtherProviderIdentifierTypeCode49 { get; set; }
		public string OtherProviderIdentifierState49 { get; set; }
		public string OtherProviderIdentifierIssuer49 { get; set; }
		public string OtherProviderIdentifier50 { get; set; }
		public string OtherProviderIdentifierTypeCode50 { get; set; }
		public string OtherProviderIdentifierState50 { get; set; }
		public string OtherProviderIdentifierIssuer50 { get; set; }
		public string IsSoleProprietor { get; set; }
		public string IsOrganizationSubpart { get; set; }
		public string ParentOrganizationLbn { get; set; }
		public string ParentOrganizationTin { get; set; }
		public string AuthorizedOfficialNamePrefixText { get; set; }
		public string AuthorizedOfficialNameSuffixText { get; set; }
		public string AuthorizedOfficialCredentialText { get; set; }
		public string HealthcareProviderTaxonomyGroup1 { get; set; }
		public string HealthcareProviderTaxonomyGroup2 { get; set; }
		public string HealthcareProviderTaxonomyGroup3 { get; set; }
		public string HealthcareProviderTaxonomyGroup4 { get; set; }
		public string HealthcareProviderTaxonomyGroup5 { get; set; }
		public string HealthcareProviderTaxonomyGroup6 { get; set; }
		public string HealthcareProviderTaxonomyGroup7 { get; set; }
		public string HealthcareProviderTaxonomyGroup8 { get; set; }
		public string HealthcareProviderTaxonomyGroup9 { get; set; }
		public string HealthcareProviderTaxonomyGroup10 { get; set; }
		public string HealthcareProviderTaxonomyGroup11 { get; set; }
		public string HealthcareProviderTaxonomyGroup12 { get; set; }
		public string HealthcareProviderTaxonomyGroup13 { get; set; }
		public string HealthcareProviderTaxonomyGroup14 { get; set; }

		public string HealthcareProviderTaxonomyGroup15 { get; set; }
	}
}